### ISSUE TITLE
Ability to disable tooltips all together

### ISSUE THREAD

**Issue by ericjohnf** [alexandersimoes/d3plus#263]
Would it be possible to turn off the tooltip functionality all together? Something along the lines of 
```javascript
.tooltip([{"display": false}])
```

For anyone else waiting a CSS work-around might look like
```css
.d3plus_tooltip {
    display: none !important;
}
```
